# Cloudflare Pages configuration
name = "plumbersbasingstoke-co-uk"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-20"

[[d1_databases]]
binding = "DB"
database_name = "basingstoke-leads"
database_id = "cace3f66-7ec1-448b-878b-194a83dbba1e"
